# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "react"
      - dependency-name: "@types/react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react-dom"
      - dependency-name: "react-router"
      - dependency-name: "@types/react-router"
      - dependency-name: "react-router-dom"
      - dependency-name: "@types/react-router-dom"
      - dependency-name: "webpack"
        versions: ["5.x"]
      - dependency-name: "react-markdown"
        versions: ["7.x","8.x"]
      - dependency-name: "remark-frontmatter"
        versions: ["4.x"]
      - dependency-name: "remark-gfm"
        versions: ["2.x","3.x"]
      - dependency-name: "@date-io/date-fns"
        versions: ["2.x"]

